version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: library_user
      POSTGRES_PASSWORD: library_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:11.14.0
    container_name: flyway
    command: migrate
#    environment:
#      - FLYWAY_URL=jdbc:postgresql://postgres:5432/library_db
#      - FLYWAY_USER=library_user
#      - FLYWAY_PASSWORD=library_password
#      - FLYWAY_SCHEMAS=public
#      - FLYWAY_LOCATIONS=filesystem:/flyway/sql
    volumes:
      - ./flyway.conf:/flyway/conf/flyway.conf
      - ./sql:/flyway/sql
    depends_on:
      - postgres


volumes:
  postgres_data: