name: Auto Database Migration
on:
  push:
    branches: [main]
    paths: ['sql/**']

jobs:
  migrate:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: library_db
          POSTGRES_USER: library_user
          POSTGRES_PASSWORD: library_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Flyway Migration
        run: |
          docker run --rm \
            -v $PWD/sql:/flyway/sql \
            -v $PWD/flyway.conf:/flyway/conf/flyway.conf \
            flyway/flyway:11.14.0 migrate
        env:
          FLYWAY_URL: "jdbc:postgresql://postgres:5432/library_db"
          FLYWAY_USER: "library_user"
          FLYWAY_PASSWORD: "library_password"