name: Build Flyway Image
on:
  push:
    branches: [main, 'feature/*', 'feature/add_flyway']
#    paths: ['sql/**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Flyway image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/burito2021/library_db:latest

      - name: Build and push PostgreSQL image with initial schema
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.postgres
          push: true
          tags: ghcr.io/burito2021/library_db-postgres:15
